version: "3"
services:
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: admin
    deploy:
        replicas: 1
        restart_policy:
          condition: on-failure
    ports:
      - "27017:27017"
    networks:
      - chat-net
  # authentication-service:
  #   image: yoshuag11/authentication-service:1.0
  #   deploy:
  #       replicas: 1
  #       restart_policy:
  #         condition: on-failure
  #   ports:
  #     - "3002:3002"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - chat-net
  # api:
  #   image: yoshuag11/api:1.0
  #   deploy:
  #       replicas: 1
  #       restart_policy:
  #         condition: on-failure
  #   ports:
  #     - "3001:3001"
  #   depends_on:
  #     - mongo
  #   networks:
  #     - chat-net
  # chat:
  #   image: yoshuag11/chat:1.2
  #   deploy:
  #       replicas: 1
  #       restart_policy:
  #         condition: on-failure
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - mongo
  #     - api
  #   networks:
  #     - chat-net
networks:
  chat-net: